import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/shared";
import { Sidebar } from "@/shared/ui/sidebar/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {/*Need to fix that */}
        <div style={{ display: "flex" }}>
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
