import type { Metadata } from "next";
import React from "react";
import { Header } from "@/shared";
import { Sidebar } from "@/shared/ui/sidebar/sidebar";
import { Roboto_Flex } from "next/font/google";
import "./globals.css";

const roboto = Roboto_Flex({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <Header />
        {/*Need to fix that */}
        <div style={{ display: "flex" }}>
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
